### ISSUE TITLE
Proposal : Granular Log configuration combination

### ISSUE THREAD

**Issue by tsimbalar** [serilog/serilog#1038]
*Help needed to find a better issue title :p*

In this issue I propose a **new feature** in which we could extend the way the `LoggerConfiguration.ReadFrom.*` work in order to support finer control over which settings are declared "in the code" and which settings are declared "in app settings" (or any other source of `KayValuePair`s).

## Objective
What I would like is a way to define most of the logging configuration in code (with the .NET fluent API), but still let the **possibility to change/override some parts of this logging configuration at runtime**, for instance, reading a configuration file, or another source.

For instance, I would like to be able to define a *baseline* logging configuration as such in C# : 

```csharp
new LoggerConfiguration()
    .MinimumLevel.Debug()
    .MinimulLevel.Override("MyApp.Controllers", LogEventLevel.Warning)
    .WriteTo.RollingFile(@"C:\temp\whatever.log", restrictedToMinimumLevel:LogEventLevel.Information)
    .CreateLogger()
```
... but be able to declare the *log file path* in a config file, or override the *MinimumLevel* in some environments.
```xml
<appSettings>
  <add key="serilog:minimum-level" name="Warning" />
  <add key="serilog:write-to:RollingFile.pathFormat" name="D:\another\location.log" />
</appSettings>
```

## Current Limitation
The current way to provide parameters at *runtime* is to rely on some of the `ReadFrom.*` methods, but those can only *add* on top of a `LoggerConfiguration`, but not change the configuration defined in code (namely override parameters of the sinks for instance)

The workaround would be, in that case, to explicitely write the code that will read a specific `appSetting` and pass the runtime value to the `LoggerConfiguration` construction calls.

## Proposed solution(s)
What I am trying to achieve is to have more fine-grained access to every parameter that ends up being used in the `LoggerConfiguration` method invocations. This is pretty difficult to do when dealing with method calls, but the `KeyValuePair` already pretty much divides every parameter in individual chunk, so I believe we could manage to take advantage of that as an extension point.

Taking inspiration from the way *AspNetCore Configuration* are additive (first json, then environment variables etc ...), the idea would be, to : 
1. define the baseline configuration in terms of individual `KeyValuePair`s (like `"minimum-level"="Warning"` or `"write-to:RollingFile.pathFormat"="D:\another\location.log"`)
2. add to this list another set of `KeyValuePair`s that can add new values, or override the values of the previous
3. possibly add yet another source of settings
4. merge all those settings, with the last added ones overriding the ones defined earlier

Here is a code snippet of something that show the raw idea, and is doable as of now, based on the existing APIs : 

```csharp
var baselineConfig = new Dictionary<string, string>{
    {"minimum-level", "Debug"},
    {"using:RollingFile", "Serilog.Sinks.RollingFile"},
    {"write-to:RollingFile.pathFormat", "default-path-{Date}.txt"},
}

// supposedly, appsetting contains 
// <add key="serilog:write-to:RollingFile.pathFormat" value="anotherPath.log" />
// <add key="serilog:minimum-level:override:Microsoft" value="Warning" />
var runtimeOverrides = ReadFromAppSettings();

// values defined "last" win
var combined= Combine(baselineConfig, runtimeOverrides);

// at this point, combined looks like : 
//new Dictionary<string, string>{
//    {"minimum-level", "Debug"},
//    {"using:RollingFile", "Serilog.Sinks.RollingFile"},
//    {"write-to:RollingFile.pathFormat", "anotherPath.log"},
//    {"minimum-level:override:Microsoft", "Warning"},
//}

var logger = new LoggerConfiguration()
    .ReadFrom.KeyValuePairs(combined)
    .CreateLogger();
```

This could first be improved to maybe provide a more fluent API plugged onto `ReadFrom` that would look like this : 

```csharp
var baselineConfig = new Dictionary<string, string>{
    {"minimum-level", "Debug"},
    {"using:RollingFile", "Serilog.Sinks.RollingFile"},
    {"write-to:RollingFile.pathFormat", "default-path-{Date}.txt"},
}

// supposedly, appsetting contains 
// <add key="serilog:write-to:RollingFile.pathFormat" value="anotherPath.log" />
// <add key="serilog:minimum-level:override:Microsoft" value="Warning" />
var logger = new LoggerConfiguration()
    .ReadFrom.Combined(x => x
        .AddKeyValuePairs(baselineConfig)
        .AddKeyValuePair("minimum-level", "Error")
        .AddAppSettings())  
    .CreateLogger();
```

Now, that's still very *string-y*, so another possible improvement would be to actually generate the `KeyValuePair`s from the code, (basically the opposite of what we are doing when converting `appSettings` into method calls) ... this is possible hacking around expression trees, and could lead to something like this : 

```csharp
// supposedly, appsetting contains 
// <add key="serilog:write-to:RollingFile.pathFormat" value="anotherPath.log" />
// <add key="serilog:minimum-level:override:Microsoft" value="Warning" />
var logger = new LoggerConfiguration()
    .ReadFrom.Combined(x => x
        .AddExpression(lc => lc  
            .MinimumLevel.Debug
            .WriteTo.RollingFile("default-path-{Date}.txt"))
        .AddAppSettings())  
    .CreateLogger();

// AddExpression takes as parameter a : 
// Expression<Func<LoggerConfiguration, LoggerConfiguration>>
```

# Implementation
I have started to work on this ... here are the remaining tasks : 

- [ ] Core infrastructure and extension points for *combined settings* - see this PR #1041 
- [ ] Specific support for *AppSettings* so that hard-coded settings can be overriden in `<appsettings>` - see this issue serilog/serilog-settings-appsettings#19
- [ ] Expression-tree overload so that *key-value* settings can be defined using the Code API - see issue #1043 

## Call for feedback
So anyways, I have a basic Proof of Concept working here https://github.com/tsimbalar/serilog/blob/769197068eab9cb0a1653e2b9d0fa9ae21b9b132/test/Serilog.Tests/Settings/KeyValuePairSettingsBuilderTests.cs and there https://github.com/tsimbalar/serilog/blob/769197068eab9cb0a1653e2b9d0fa9ae21b9b132/test/Serilog.Tests/Settings/AppSettingsFromExpressionTests.cs  , and I'm probably going to keep on playing with it a bit, but I wanted to know  : 
1. if that would be relevant to have globally available
2. if anyone had suggestions for improvement to make the API as friendly as possible
3. if this should be part of Serilog *core* or a separate package
4. if what I'm trying to do has not already be done :p

*Thanks for reading !*

**Comment by nblumhardt** [comment]
I've only had a quick glance through this, but in the interests of early feedback :-)

 1. Yes!
 2. I'd have to dig deeper to do this
 3. A separate package seems like a good starting point for experimentation; eventually, having some mechanism in the core to allow providers like _Serilog.Settings.AppSettings_ to hook into this would be great
 4. Haven't seen it yet, although it's close to the way _Microsoft.Extensions.Configuration_ is designed

**Comment by tsimbalar** [comment]
Regarding the *packaging* part, here are my plans : 
- in serilog/serilog : implement the abstractions / base infrastructure / extension points to support that
- in serilog/serilog-settings-appsettings : the implementation to add settings from the `<appSettings>` 
- in serilog/serilog : implement the *reflection*/*expressions trees* thing if it does not mean adding/changing the dependencies (that's a bit more easier, because we can then reuse the constants from `KeyValuePairSettings` )

I had a look at `Microsoft.Extensions.Configuration` a bit, but I guess adding a dependency to `Microsoft.Extensions.Configuration.Abstractions` in Serilog is a **no go**, right ?

**Comment by tsimbalar** [comment]
# Implementation
I have started to work on this ... here are the remaining tasks : 

- [ ] Core infrastructure and extension points for *combined settings* - see this PR #1041 
- [ ] Specific support for *AppSettings* so that hard-coded settings can be overriden in `<appsettings>` - TODO
- [ ] Expression-tree overload so that *key-value* settings can be defined using the Code API - TODO

**Comment by RehanSaeed** [comment]
If this is going to be a separate package, I don't see why it would be a problem to take a dependency on `Microsoft.Extensions.Configuration` rather than reinventing the wheel. You would also get all of the configuration addon packages from Microsoft (JSON, environment variables) and third parties have developed for free (yaml, ini, Azure key vault and docker secrets come to mind).

Adding support for old school `appSettings` could just be an addon package for `Microsoft.Extensions.Configuration`, such a thing might even already exist.

With all this said, I realize that I'm biased, I've been a heavy user of ASP.NET Core. Using this package might not be as nice for other users, although this package is supposed to be generic.

**Comment by tsimbalar** [comment]
@RehanSaeedthat makes a lot of sense 😎 !  , but just to be sure :  
1. wouldn't that bring confusion with the existing [serilog/serilog-settings-configuration](https://github.com/serilog/serilog-settings-configuration) project ? 
2. wouldn't that limit its use to only .NET Core apps and be unusable for older .NET Framework apps ? (I'm pretty clueless about .NET Core so far, still haven't jumped in it yet)
3. wouldn't that be misleading and have people believe all the features from `Microsoft.Extensions.Configuration` are supported ? (I'm think about the `reloadToken` and stuff like that, which may or may not work for us, or the `Set()` methods)

I must say I'm a bit confused, because [serilog/serilog-settings-configuration](https://github.com/serilog/serilog-settings-configuration) reads from a [`IConfiguration`](https://github.com/aspnet/Configuration/blob/dev/src/Config.Abstractions/IConfiguration.cs) object, but I think, in our case, we would want to accept an [`IConfigurationProvider`](https://github.com/aspnet/Configuration/blob/dev/src/Config.Abstractions/IConfigurationProvider.cs) in order to do the *combination* of multiple sources.

I believe @nblumhardt had something in mind regarding all that too, with that question sent in [gitter](https://gitter.im/serilog/serilog) : 
![image](https://user-images.githubusercontent.com/160544/31662809-2ca44a6c-b340-11e7-9183-a2276e925979.png)

**Comment by RehanSaeed** [comment]
1. I always thought this feature should exist within the `serilog/serilog-settings-configuration` project, which is why i raised an issue there raising this [exact problem](https://github.com/serilog/serilog-settings-configuration/issues/26) some time ago.
2. `Microsoft.Extensions.Configuration` version 2.0 relies on `netstandard2.0` which means .NET 4.6.1 or .NET Core 2.0. `Microsoft.Extensions.Configuration` version 1.1.2 relies on `netstandard1.1` which would expand the supported frameworks considerably.
3. Reload is a cool feature but I've never found a use for it. It only works in ASP.NET Core if you especially code for it i.e. use `IOptionsSnapshot<T>` instead of `IOptions<T>`. It also has a slight performance impact.

**Comment by nblumhardt** [comment]
Thanks for the link to the earlier ticket, @RehanSaeed - I think the direction we're going here will enable what you have in mind, we should use your example to validate the design 👍 

I don't really feel comfortable with a deep dependency on _Microsoft.Extensions.Configuration_; it's obviously important to have great support for it, but I wouldn't be surprised if there is more change/churn there down the track. We'd give up our control over platform support, and end up pulling in whatever transitive dependencies _m.e.Configuration_ adopts in the future.

**Comment by tsimbalar** [comment]
FWIW, this just came out (https://blogs.msdn.microsoft.com/dotnet/2017/10/17/announcing-the-net-framework-4-7-1/) :

> Configuration builders
> Configuration builders allow developers to inject and build configuration for applications at runtime, allowing configuration data to be pulled from sources beyond the traditional .config file.  In previous versions of the .NET Framework, configuration has been static. Applications only draw configuration data from a limited chain of .config files. With Configuration Builders, applications can apply a custom-defined set of builders to any section of config. These builders are free to modify the configuration data contained in the given config section, or build it entirely from scratch – possibly drawing new data from new sources that are not static files.
> To use the Configuration Builders feature, developers simply need to declare builders in config, then apply them to configuration sections with the ConfigBuilders tag.

> Here are some code samples that will enable you to declare, use and apply configuration builders.
https://gist.github.com/preetikr/55335d117f9f5f992d7c07796fe18bcf#file-net471_configuration_samples-xml 

Maybe it would be good to have it in mind when designing the "combination of multiple sources", although I don't expect a massive move to .NET 4.7.1 straight way :p

**Comment by RehanSaeed** [comment]
@nblumhardt I find myself agreeing with you but I feel that there is a case for some kind of ASP.NET Core specific package that relies on `Microsoft.Extensions.Configuration` aswell.

**Comment by nblumhardt** [comment]
https://github.com/serilog/serilog-settings-combined created, let's move discussion there. Cheers!
