### ISSUE TITLE
Final v2 Release Checklist

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog#590]
- [ ] Publish some formal compatibility info
 - [ ] Check/finalize v2 prerelease build numbering
 - [x] Publish from AppVeyor
 - [x] Move over to the new netstandard TFM once it's supported (see https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/standard-platform.md for details)
 - [x] Ensure dependencies in `project.json` are pruned accordingly.
 - [ ] A view of open new issues across the Serilog repositories
 - [x] Review doco on wiki given DNX changes

Ensure all the sinks have
 - [ ] Dev Branch for new work
 - [ ] AppVeyor builds for beta packages.
 - [ ] appveyor.yml based build configuration
 - [ ] a single (or one of a small few) common build script
 - [ ] verify the target framework versions are the ones we want to support
 - [ ] .gitattributes files :-)

This list may grow over time; from #535.

**Comment by merbla** [comment]
- [ ] Improve the doco/story on OSX (Maybe post v2 Beta)

**Comment by nblumhardt** [comment]
Ensure all the sinks have
 - [] Dev Branch for new work
 - [] AppVeyor builds for beta packages.
 - [] appveyor.yml based build configuration
 - [] a single (or one of a small few) common build script
 - [] verify the target framework versions are the ones we want to support

**Comment by merbla** [comment]
A list of repos for easy access.....

https://github.com/serilog/serilog
https://github.com/serilog/serilog-generator
https://github.com/serilog/serilog-sinks-mongodb
https://github.com/serilog/serilog-sinks-applicationinsights
https://github.com/serilog/serilog-sinks-splunk
https://github.com/serilog/serilog-sinks-loggly
https://github.com/serilog/serilog-sinks-azuredocumentdb
https://github.com/serilog/serilog-sinks-azureeventhub
https://github.com/serilog/serilog-sinks-azuretablestorage
https://github.com/serilog/serilog-sinks-couchbase
https://github.com/serilog/serilog-sinks-couchdb
https://github.com/serilog/serilog-sinks-elasticsearch
https://github.com/serilog/serilog-sinks-elmahio
https://github.com/serilog/serilog-sinks-email
https://github.com/serilog/serilog-sinks-eventlog
https://github.com/serilog/serilog-sinks-glimpse
https://github.com/serilog/serilog-sinks-log4net
https://github.com/serilog/serilog-sinks-logentries
https://github.com/serilog/serilog-sinks-loggr
https://github.com/serilog/serilog-sinks-xamarin
https://github.com/serilog/serilog-sinks-mssqlserver
https://github.com/serilog/serilog-sinks-nlog
https://github.com/serilog/serilog-sinks-ravendb
https://github.com/serilog/serilog-sinks-raygun
https://github.com/serilog/serilog-sinks-seq
https://github.com/serilog/serilog-sinks-xsockets
https://github.com/serilog/serilog-sinks-signalr
https://github.com/serilog/serilog-net35
https://github.com/serilog/serilog-sinks-exceptionless
https://github.com/serilog/serilog-sinks-literate
https://github.com/serilog/serilog-sinks-datadog
https://github.com/serilog/serilog-sinks-rethinkdb
https://github.com/serilog/serilog-sinks-amazonkinesis
https://github.com/serilog/serilog-dnx-prerelease
https://github.com/serilog/serilog-extensions-logging
https://github.com/serilog/serilog-settings-configuration
https://github.com/serilog/serilog-sinks-dynamodb
https://github.com/serilog/serilog-docs
https://github.com/serilog/serilog-docker
https://github.com/serilog/serilog-sinks-console
https://github.com/serilog/serilog-sinks-file
https://github.com/serilog/serilog-sinks-coloredconsole
https://github.com/serilog/serilog-sinks-observable
https://github.com/serilog/serilog-sinks-periodicbatching
https://github.com/serilog/serilog-sinks-rollingfile
https://github.com/serilog/serilog-sinks-textwriter
https://github.com/serilog/serilog-sinks-trace
https://github.com/serilog/serilog-enrichers-environment
https://github.com/serilog/serilog-enrichers-process
https://github.com/serilog/serilog-enrichers-thread
https://github.com/serilog/serilog-settings-appsettings

**Comment by nblumhardt** [comment]
@merbla since we've split out #795 do we still need this issue? I would love to see everything updated en masse, but time constraints mean that in reality we'll probably just accept PRs as they come in. What do you think?

**Comment by merbla** [comment]
Nup, I think we are there.  Anything we missed can flush out in due course.

**Comment by Serjster** [comment]
@nblumhardt  Can I confirm that Serilog v2 (.NET Core) is now out of beta and is now RTM?

**Comment by nblumhardt** [comment]
@Serjster yes, that's the case :+1:
